version: "2"

linters:
  default: none
  enable:
    - bodyclose # https://github.com/timakin/bodyclose
    - errcheck # Mandatory. Do not disable.
    - govet
    - nolintlint
    - ineffassign # Mandatory. Do not disable.
    - staticcheck # Mandatory. Do not disable.
    - unused

  settings:
    errcheck:
      exclude-functions:
        - (io.Closer).Close
        - (io.ReadCloser).Close
        - (*os.File).Close
        - (*io.PipeWriter).Close
        - (*io.PipeReader).Close
        - (go.etcd.io/etcd/client/v3.Watcher).Close
        - (*github.com/gubernator-io/gubernator/v2.WorkerPool).Close

    govet:
      disable:
        - shadow
        - fieldalignment
      enable-all: true
    staticcheck:
      checks:
        - all
        - -SA1019
        - -ST1003

issues:
  # Maximum issues count per one linter. Set to 0 to disable. Default is 50.
  max-issues-per-linter: 0

  # Maximum count of issues with the same text. Set to 0 to disable. Default is 3.
  max-same-issues: 50

formatters:
  enable:
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$

run:
  # include test files or not, default is true
  tests: true

  # Timeout for analysis, e.g. 30s, 5m.
  # Default: 1m
  timeout: 5m
