version: '3'
services:
  gubernator-1:
    image: ghcr.io/gubernator-io/gubernator:latest
    entrypoint: "/gubernator"
    environment:
      # Basic member-list config
      - GUBER_GRPC_ADDRESS=0.0.0.0:1051
      - GUBER_HTTP_ADDRESS=0.0.0.0:1050
      - GUBER_ADVERTISE_ADDRESS=gubernator-1:1051
      - GUBER_MEMBERLIST_KNOWN_NODES=gubernator-1
      - GUBER_MEMBERLIST_SECRET_KEYS=eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHg=
      # TLS config
      - GUBER_TLS_CA=/etc/tls/ca.pem
      - GUBER_TLS_KEY=/etc/tls/gubernator.key
      - GUBER_TLS_CERT=/etc/tls/gubernator.pem
      - GUBER_TLS_CLIENT_AUTH=require-and-verify
    ports:
      - "1051:1051"
      - "1050:1050"
    volumes:
      - ${PWD}/contrib/certs:/etc/tls

  gubernator-2:
    image: ghcr.io/gubernator-io/gubernator:latest
    entrypoint: "/gubernator"
    environment:
      # Basic member-list config
      - GUBER_GRPC_ADDRESS=0.0.0.0:1051
      - GUBER_HTTP_ADDRESS=0.0.0.0:1050
      - GUBER_ADVERTISE_ADDRESS=gubernator-2:1051
      - GUBER_MEMBERLIST_KNOWN_NODES=gubernator-1
      - GUBER_MEMBERLIST_SECRET_KEYS=eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHg=
      # TLS config
      - GUBER_TLS_CA=/etc/tls/ca.pem
      - GUBER_TLS_KEY=/etc/tls/gubernator.key
      - GUBER_TLS_CERT=/etc/tls/gubernator.pem
      - GUBER_TLS_CLIENT_AUTH=require-and-verify
    ports:
      - "1151:1051"
      - "1150:1050"
    volumes:
      - ${PWD}/contrib/certs:/etc/tls

  gubernator-3:
    image: ghcr.io/gubernator-io/gubernator:latest
    entrypoint: "/gubernator"
    environment:
      # Basic member-list config
      - GUBER_GRPC_ADDRESS=0.0.0.0:1051
      - GUBER_HTTP_ADDRESS=0.0.0.0:1050
      - GUBER_ADVERTISE_ADDRESS=gubernator-3:1051
      - GUBER_MEMBERLIST_KNOWN_NODES=gubernator-1
      - GUBER_MEMBERLIST_SECRET_KEYS=eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHg=
      # TLS config
      - GUBER_TLS_CA=/etc/tls/ca.pem
      - GUBER_TLS_KEY=/etc/tls/gubernator.key
      - GUBER_TLS_CERT=/etc/tls/gubernator.pem
      - GUBER_TLS_CLIENT_AUTH=require-and-verify
    ports:
      - "1251:1051"
      - "1250:1050"
    volumes:
      - ${PWD}/contrib/certs:/etc/tls

  gubernator-4:
    image: ghcr.io/gubernator-io/gubernator:latest
    entrypoint: "/gubernator"
    environment:
      # Basic member-list config
      - GUBER_DEBUG=true
      - GUBER_GRPC_ADDRESS=0.0.0.0:1051
      - GUBER_HTTP_ADDRESS=0.0.0.0:1050
      - GUBER_ADVERTISE_ADDRESS=gubernator-4:1051
      - GUBER_MEMBERLIST_KNOWN_NODES=gubernator-1
      - GUBER_MEMBERLIST_SECRET_KEYS=eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHg=
      # TLS config
      - GUBER_TLS_CA=/etc/tls/ca.pem
      - GUBER_TLS_KEY=/etc/tls/gubernator.key
      - GUBER_TLS_CERT=/etc/tls/gubernator.pem
      - GUBER_TLS_CLIENT_AUTH=require-and-verify
    ports:
      - "1351:1051"
      - "1350:1050"
    volumes:
      - ${PWD}/contrib/certs:/etc/tls
