services:
  gubernator-1:
    image: ghcr.io/gubernator-io/gubernator:latest
    entrypoint: "/gubernator"
    environment:
      # The address GRPC requests will listen on
      - GUBER_GRPC_ADDRESS=0.0.0.0:1051
      # The address HTTP requests will listen on
      - GUBER_HTTP_ADDRESS=0.0.0.0:1050
      # The address that is advertised to other peers
      - GUBER_ADVERTISE_ADDRESS=gubernator-1:1051
      # A comma separated list of known gubernator nodes
      - GUBER_MEMBERLIST_KNOWN_NODES=gubernator-1
      #- GUBER_DATA_CENTER=us-east-1
    ports:
      - "1051:1051"
      - "1050:1050"

  gubernator-2:
    image: ghcr.io/gubernator-io/gubernator:latest
    entrypoint: "/gubernator"
    environment:
      # The address GRPC requests will listen on
      - GUBER_GRPC_ADDRESS=0.0.0.0:1051
      # The address HTTP requests will listen on
      - GUBER_HTTP_ADDRESS=0.0.0.0:1050
      # The address that is advertised to other peers
      - GUBER_ADVERTISE_ADDRESS=gubernator-2:1051
      # A comma separated list of known gubernator nodes
      - GUBER_MEMBERLIST_KNOWN_NODES=gubernator-1
      #- GUBER_DATA_CENTER=us-east-1
    ports:
      - "1151:1051"
      - "1150:1050"

  gubernator-3:
    image: ghcr.io/gubernator-io/gubernator:latest
    entrypoint: "/gubernator"
    environment:
      # The address GRPC requests will listen on
      - GUBER_GRPC_ADDRESS=0.0.0.0:1051
      # The address HTTP requests will listen on
      - GUBER_HTTP_ADDRESS=0.0.0.0:1050
      # The address that is advertised to other peers
      - GUBER_ADVERTISE_ADDRESS=gubernator-3:1051
      # A comma separated list of known gubernator nodes
      - GUBER_MEMBERLIST_KNOWN_NODES=gubernator-1
      #- GUBER_DATA_CENTER=us-west-2
    ports:
      - "1251:1051"
      - "1250:1050"

  gubernator-4:
    image: ghcr.io/gubernator-io/gubernator:latest
    entrypoint: "/gubernator"
    environment:
      - GUBER_DEBUG=true
      # The address GRPC requests will listen on
      - GUBER_GRPC_ADDRESS=0.0.0.0:1051
      # The address HTTP requests will listen on
      - GUBER_HTTP_ADDRESS=0.0.0.0:1050
      # The address that is advertised to other peers
      - GUBER_ADVERTISE_ADDRESS=gubernator-4:1051
      # A Comma separated list of known gubernator nodes
      - GUBER_MEMBERLIST_KNOWN_NODES=gubernator-1,gubernator-2
      #- GUBER_DATA_CENTER=us-west-2
      #- GUBER_METRIC_FLAGS=golang,os
    ports:
      - "1351:1051"
      - "1350:1050"
