//
//Copyright 2018-2022 Mailgun Technologies Inc
//
//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: envoy_policy.proto

package gubernator

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	EnvoyPolicyV1_ApplyPolicies_FullMethodName  = "/pb.gubernator.EnvoyPolicyV1/ApplyPolicies"
	EnvoyPolicyV1_DeletePolicies_FullMethodName = "/pb.gubernator.EnvoyPolicyV1/DeletePolicies"
	EnvoyPolicyV1_ListPolicies_FullMethodName   = "/pb.gubernator.EnvoyPolicyV1/ListPolicies"
)

// EnvoyPolicyV1Client is the client API for EnvoyPolicyV1 service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EnvoyPolicyV1Client interface {
	// Upserts each policy; broadcasts to all known peers; returns peers that did not ack.
	ApplyPolicies(ctx context.Context, in *ApplyPoliciesReq, opts ...grpc.CallOption) (*ApplyPoliciesResp, error)
	// Tombstones each domain; same propagation as apply.
	DeletePolicies(ctx context.Context, in *DeletePoliciesReq, opts ...grpc.CallOption) (*DeletePoliciesResp, error)
	// Returns this peer's current non-tombstoned policies.
	ListPolicies(ctx context.Context, in *ListPoliciesReq, opts ...grpc.CallOption) (*ListPoliciesResp, error)
}

type envoyPolicyV1Client struct {
	cc grpc.ClientConnInterface
}

func NewEnvoyPolicyV1Client(cc grpc.ClientConnInterface) EnvoyPolicyV1Client {
	return &envoyPolicyV1Client{cc}
}

func (c *envoyPolicyV1Client) ApplyPolicies(ctx context.Context, in *ApplyPoliciesReq, opts ...grpc.CallOption) (*ApplyPoliciesResp, error) {
	out := new(ApplyPoliciesResp)
	err := c.cc.Invoke(ctx, EnvoyPolicyV1_ApplyPolicies_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *envoyPolicyV1Client) DeletePolicies(ctx context.Context, in *DeletePoliciesReq, opts ...grpc.CallOption) (*DeletePoliciesResp, error) {
	out := new(DeletePoliciesResp)
	err := c.cc.Invoke(ctx, EnvoyPolicyV1_DeletePolicies_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *envoyPolicyV1Client) ListPolicies(ctx context.Context, in *ListPoliciesReq, opts ...grpc.CallOption) (*ListPoliciesResp, error) {
	out := new(ListPoliciesResp)
	err := c.cc.Invoke(ctx, EnvoyPolicyV1_ListPolicies_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EnvoyPolicyV1Server is the server API for EnvoyPolicyV1 service.
// All implementations should embed UnimplementedEnvoyPolicyV1Server
// for forward compatibility
type EnvoyPolicyV1Server interface {
	// Upserts each policy; broadcasts to all known peers; returns peers that did not ack.
	ApplyPolicies(context.Context, *ApplyPoliciesReq) (*ApplyPoliciesResp, error)
	// Tombstones each domain; same propagation as apply.
	DeletePolicies(context.Context, *DeletePoliciesReq) (*DeletePoliciesResp, error)
	// Returns this peer's current non-tombstoned policies.
	ListPolicies(context.Context, *ListPoliciesReq) (*ListPoliciesResp, error)
}

// UnimplementedEnvoyPolicyV1Server should be embedded to have forward compatible implementations.
type UnimplementedEnvoyPolicyV1Server struct {
}

func (UnimplementedEnvoyPolicyV1Server) ApplyPolicies(context.Context, *ApplyPoliciesReq) (*ApplyPoliciesResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApplyPolicies not implemented")
}
func (UnimplementedEnvoyPolicyV1Server) DeletePolicies(context.Context, *DeletePoliciesReq) (*DeletePoliciesResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeletePolicies not implemented")
}
func (UnimplementedEnvoyPolicyV1Server) ListPolicies(context.Context, *ListPoliciesReq) (*ListPoliciesResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPolicies not implemented")
}

// UnsafeEnvoyPolicyV1Server may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EnvoyPolicyV1Server will
// result in compilation errors.
type UnsafeEnvoyPolicyV1Server interface {
	mustEmbedUnimplementedEnvoyPolicyV1Server()
}

func RegisterEnvoyPolicyV1Server(s grpc.ServiceRegistrar, srv EnvoyPolicyV1Server) {
	s.RegisterService(&EnvoyPolicyV1_ServiceDesc, srv)
}

func _EnvoyPolicyV1_ApplyPolicies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyPoliciesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnvoyPolicyV1Server).ApplyPolicies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EnvoyPolicyV1_ApplyPolicies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnvoyPolicyV1Server).ApplyPolicies(ctx, req.(*ApplyPoliciesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _EnvoyPolicyV1_DeletePolicies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePoliciesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnvoyPolicyV1Server).DeletePolicies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EnvoyPolicyV1_DeletePolicies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnvoyPolicyV1Server).DeletePolicies(ctx, req.(*DeletePoliciesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _EnvoyPolicyV1_ListPolicies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPoliciesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnvoyPolicyV1Server).ListPolicies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EnvoyPolicyV1_ListPolicies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnvoyPolicyV1Server).ListPolicies(ctx, req.(*ListPoliciesReq))
	}
	return interceptor(ctx, in, info, handler)
}

// EnvoyPolicyV1_ServiceDesc is the grpc.ServiceDesc for EnvoyPolicyV1 service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EnvoyPolicyV1_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.gubernator.EnvoyPolicyV1",
	HandlerType: (*EnvoyPolicyV1Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ApplyPolicies",
			Handler:    _EnvoyPolicyV1_ApplyPolicies_Handler,
		},
		{
			MethodName: "DeletePolicies",
			Handler:    _EnvoyPolicyV1_DeletePolicies_Handler,
		},
		{
			MethodName: "ListPolicies",
			Handler:    _EnvoyPolicyV1_ListPolicies_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "envoy_policy.proto",
}
