//
//Copyright 2018-2022 Mailgun Technologies Inc
//
//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        (unknown)
// source: envoy_policy.proto

package gubernator

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// What a domain does with a descriptor that carries no limit override.
type MissingLimitAction int32

const (
	// Report the descriptor OVER_LIMIT without creating a rate limit.
	MissingLimitAction_DENY MissingLimitAction = 0
	// Report the descriptor OK without creating a rate limit.
	MissingLimitAction_ALLOW MissingLimitAction = 1
	// Fail the whole ShouldRateLimit call with InvalidArgument.
	MissingLimitAction_ERROR MissingLimitAction = 2
)

// Enum value maps for MissingLimitAction.
var (
	MissingLimitAction_name = map[int32]string{
		0: "DENY",
		1: "ALLOW",
		2: "ERROR",
	}
	MissingLimitAction_value = map[string]int32{
		"DENY":  0,
		"ALLOW": 1,
		"ERROR": 2,
	}
)

func (x MissingLimitAction) Enum() *MissingLimitAction {
	p := new(MissingLimitAction)
	*p = x
	return p
}

func (x MissingLimitAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MissingLimitAction) Descriptor() protoreflect.EnumDescriptor {
	return file_envoy_policy_proto_enumTypes[0].Descriptor()
}

func (MissingLimitAction) Type() protoreflect.EnumType {
	return &file_envoy_policy_proto_enumTypes[0]
}

func (x MissingLimitAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MissingLimitAction.Descriptor instead.
func (MissingLimitAction) EnumDescriptor() ([]byte, []int) {
	return file_envoy_policy_proto_rawDescGZIP(), []int{0}
}

type DomainPolicy struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The RLS domain this policy applies to. Required, non-empty.
	Domain string `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	// Algorithm used to count every rate limit in this domain.
	Algorithm Algorithm `protobuf:"varint,2,opt,name=algorithm,proto3,enum=pb.gubernator.Algorithm" json:"algorithm,omitempty"`
	// Behavior bitflags OR'd onto every rate limit in this domain.
	Behavior       int32              `protobuf:"varint,3,opt,name=behavior,proto3" json:"behavior,omitempty"`
	OnMissingLimit MissingLimitAction `protobuf:"varint,4,opt,name=on_missing_limit,json=onMissingLimit,proto3,enum=pb.gubernator.MissingLimitAction" json:"on_missing_limit,omitempty"`
	// Set by the server on apply; a client-supplied value is ignored.
	// Wall-clock milliseconds ratcheted above the previously stored version.
	Version int64 `protobuf:"varint,5,opt,name=version,proto3" json:"version,omitempty"`
	// Advertise address of the applying peer. Breaks ties between equal
	// versions. Set by the server on apply; a client-supplied value is ignored.
	Origin string `protobuf:"bytes,6,opt,name=origin,proto3" json:"origin,omitempty"`
}

func (x *DomainPolicy) Reset() {
	*x = DomainPolicy{}
	if protoimpl.UnsafeEnabled {
		mi := &file_envoy_policy_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DomainPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DomainPolicy) ProtoMessage() {}

func (x *DomainPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_envoy_policy_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DomainPolicy.ProtoReflect.Descriptor instead.
func (*DomainPolicy) Descriptor() ([]byte, []int) {
	return file_envoy_policy_proto_rawDescGZIP(), []int{0}
}

func (x *DomainPolicy) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *DomainPolicy) GetAlgorithm() Algorithm {
	if x != nil {
		return x.Algorithm
	}
	return Algorithm_TOKEN_BUCKET
}

func (x *DomainPolicy) GetBehavior() int32 {
	if x != nil {
		return x.Behavior
	}
	return 0
}

func (x *DomainPolicy) GetOnMissingLimit() MissingLimitAction {
	if x != nil {
		return x.OnMissingLimit
	}
	return MissingLimitAction_DENY
}

func (x *DomainPolicy) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *DomainPolicy) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

type ApplyPoliciesReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Policies []*DomainPolicy `protobuf:"bytes,1,rep,name=policies,proto3" json:"policies,omitempty"`
}

func (x *ApplyPoliciesReq) Reset() {
	*x = ApplyPoliciesReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_envoy_policy_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ApplyPoliciesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyPoliciesReq) ProtoMessage() {}

func (x *ApplyPoliciesReq) ProtoReflect() protoreflect.Message {
	mi := &file_envoy_policy_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyPoliciesReq.ProtoReflect.Descriptor instead.
func (*ApplyPoliciesReq) Descriptor() ([]byte, []int) {
	return file_envoy_policy_proto_rawDescGZIP(), []int{1}
}

func (x *ApplyPoliciesReq) GetPolicies() []*DomainPolicy {
	if x != nil {
		return x.Policies
	}
	return nil
}

type ApplyPoliciesResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Every policy from the request with its assigned version and origin.
	Applied []*DomainPolicy `protobuf:"bytes,1,rep,name=applied,proto3" json:"applied,omitempty"`
	// Peers that did not acknowledge the broadcast within the timeout.
	UnreachablePeers []string `protobuf:"bytes,2,rep,name=unreachable_peers,json=unreachablePeers,proto3" json:"unreachable_peers,omitempty"`
}

func (x *ApplyPoliciesResp) Reset() {
	*x = ApplyPoliciesResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_envoy_policy_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ApplyPoliciesResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyPoliciesResp) ProtoMessage() {}

func (x *ApplyPoliciesResp) ProtoReflect() protoreflect.Message {
	mi := &file_envoy_policy_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyPoliciesResp.ProtoReflect.Descriptor instead.
func (*ApplyPoliciesResp) Descriptor() ([]byte, []int) {
	return file_envoy_policy_proto_rawDescGZIP(), []int{2}
}

func (x *ApplyPoliciesResp) GetApplied() []*DomainPolicy {
	if x != nil {
		return x.Applied
	}
	return nil
}

func (x *ApplyPoliciesResp) GetUnreachablePeers() []string {
	if x != nil {
		return x.UnreachablePeers
	}
	return nil
}

type DeletePoliciesReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Domains []string `protobuf:"bytes,1,rep,name=domains,proto3" json:"domains,omitempty"`
}

func (x *DeletePoliciesReq) Reset() {
	*x = DeletePoliciesReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_envoy_policy_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeletePoliciesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePoliciesReq) ProtoMessage() {}

func (x *DeletePoliciesReq) ProtoReflect() protoreflect.Message {
	mi := &file_envoy_policy_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePoliciesReq.ProtoReflect.Descriptor instead.
func (*DeletePoliciesReq) Descriptor() ([]byte, []int) {
	return file_envoy_policy_proto_rawDescGZIP(), []int{3}
}

func (x *DeletePoliciesReq) GetDomains() []string {
	if x != nil {
		return x.Domains
	}
	return nil
}

type DeletePoliciesResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Peers that did not acknowledge the broadcast within the timeout.
	UnreachablePeers []string `protobuf:"bytes,1,rep,name=unreachable_peers,json=unreachablePeers,proto3" json:"unreachable_peers,omitempty"`
}

func (x *DeletePoliciesResp) Reset() {
	*x = DeletePoliciesResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_envoy_policy_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeletePoliciesResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePoliciesResp) ProtoMessage() {}

func (x *DeletePoliciesResp) ProtoReflect() protoreflect.Message {
	mi := &file_envoy_policy_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePoliciesResp.ProtoReflect.Descriptor instead.
func (*DeletePoliciesResp) Descriptor() ([]byte, []int) {
	return file_envoy_policy_proto_rawDescGZIP(), []int{4}
}

func (x *DeletePoliciesResp) GetUnreachablePeers() []string {
	if x != nil {
		return x.UnreachablePeers
	}
	return nil
}

type ListPoliciesReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListPoliciesReq) Reset() {
	*x = ListPoliciesReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_envoy_policy_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListPoliciesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPoliciesReq) ProtoMessage() {}

func (x *ListPoliciesReq) ProtoReflect() protoreflect.Message {
	mi := &file_envoy_policy_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPoliciesReq.ProtoReflect.Descriptor instead.
func (*ListPoliciesReq) Descriptor() ([]byte, []int) {
	return file_envoy_policy_proto_rawDescGZIP(), []int{5}
}

type ListPoliciesResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Policies []*DomainPolicy `protobuf:"bytes,1,rep,name=policies,proto3" json:"policies,omitempty"`
}

func (x *ListPoliciesResp) Reset() {
	*x = ListPoliciesResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_envoy_policy_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListPoliciesResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPoliciesResp) ProtoMessage() {}

func (x *ListPoliciesResp) ProtoReflect() protoreflect.Message {
	mi := &file_envoy_policy_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPoliciesResp.ProtoReflect.Descriptor instead.
func (*ListPoliciesResp) Descriptor() ([]byte, []int) {
	return file_envoy_policy_proto_rawDescGZIP(), []int{6}
}

func (x *ListPoliciesResp) GetPolicies() []*DomainPolicy {
	if x != nil {
		return x.Policies
	}
	return nil
}

var File_envoy_policy_proto protoreflect.FileDescriptor

var file_envoy_policy_proto_rawDesc = []byte{
	0x0a, 0x12, 0x65, 0x6e, 0x76, 0x6f, 0x79, 0x5f, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x70, 0x62, 0x2e, 0x67, 0x75, 0x62, 0x65, 0x72, 0x6e, 0x61,
	0x74, 0x6f, 0x72, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f,
	0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x1a, 0x10, 0x67, 0x75, 0x62, 0x65, 0x72, 0x6e, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0xf9, 0x01, 0x0a, 0x0c, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x50, 0x6f,
	0x6c, 0x69, 0x63, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x12, 0x36, 0x0a, 0x09,
	0x61, 0x6c, 0x67, 0x6f, 0x72, 0x69, 0x74, 0x68, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x18, 0x2e, 0x70, 0x62, 0x2e, 0x67, 0x75, 0x62, 0x65, 0x72, 0x6e, 0x61, 0x74, 0x6f, 0x72, 0x2e,
	0x41, 0x6c, 0x67, 0x6f, 0x72, 0x69, 0x74, 0x68, 0x6d, 0x52, 0x09, 0x61, 0x6c, 0x67, 0x6f, 0x72,
	0x69, 0x74, 0x68, 0x6d, 0x12, 0x1a, 0x0a, 0x08, 0x62, 0x65, 0x68, 0x61, 0x76, 0x69, 0x6f, 0x72,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x62, 0x65, 0x68, 0x61, 0x76, 0x69, 0x6f, 0x72,
	0x12, 0x4b, 0x0a, 0x10, 0x6f, 0x6e, 0x5f, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6e, 0x67, 0x5f, 0x6c,
	0x69, 0x6d, 0x69, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x21, 0x2e, 0x70, 0x62, 0x2e,
	0x67, 0x75, 0x62, 0x65, 0x72, 0x6e, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x4d, 0x69, 0x73, 0x73, 0x69,
	0x6e, 0x67, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0e, 0x6f,
	0x6e, 0x4d, 0x69, 0x73, 0x73, 0x69, 0x6e, 0x67, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x18, 0x0a,
	0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07,
	0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x72, 0x69, 0x67, 0x69,
	0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x22,
	0x4b, 0x0a, 0x10, 0x41, 0x70, 0x70, 0x6c, 0x79, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x69, 0x65, 0x73,
	0x52, 0x65, 0x71, 0x12, 0x37, 0x0a, 0x08, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x69, 0x65, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x70, 0x62, 0x2e, 0x67, 0x75, 0x62, 0x65, 0x72,
	0x6e, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x50, 0x6f, 0x6c, 0x69,
	0x63, 0x79, 0x52, 0x08, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x69, 0x65, 0x73, 0x22, 0x77, 0x0a, 0x11,
	0x41, 0x70, 0x70, 0x6c, 0x79, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x69, 0x65, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x35, 0x0a, 0x07, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x65, 0x64, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x70, 0x62, 0x2e, 0x67, 0x75, 0x62, 0x65, 0x72, 0x6e, 0x61, 0x74,
	0x6f, 0x72, 0x2e, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x52,
	0x07, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x65, 0x64, 0x12, 0x2b, 0x0a, 0x11, 0x75, 0x6e, 0x72, 0x65,
	0x61, 0x63, 0x68, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x70, 0x65, 0x65, 0x72, 0x73, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x10, 0x75, 0x6e, 0x72, 0x65, 0x61, 0x63, 0x68, 0x61, 0x62, 0x6c, 0x65,
	0x50, 0x65, 0x65, 0x72, 0x73, 0x22, 0x2d, 0x0a, 0x11, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50,
	0x6f, 0x6c, 0x69, 0x63, 0x69, 0x65, 0x73, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x64, 0x6f,
	0x6d, 0x61, 0x69, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x64, 0x6f, 0x6d,
	0x61, 0x69, 0x6e, 0x73, 0x22, 0x41, 0x0a, 0x12, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x6f,
	0x6c, 0x69, 0x63, 0x69, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x2b, 0x0a, 0x11, 0x75, 0x6e,
	0x72, 0x65, 0x61, 0x63, 0x68, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x70, 0x65, 0x65, 0x72, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x10, 0x75, 0x6e, 0x72, 0x65, 0x61, 0x63, 0x68, 0x61, 0x62,
	0x6c, 0x65, 0x50, 0x65, 0x65, 0x72, 0x73, 0x22, 0x11, 0x0a, 0x0f, 0x4c, 0x69, 0x73, 0x74, 0x50,
	0x6f, 0x6c, 0x69, 0x63, 0x69, 0x65, 0x73, 0x52, 0x65, 0x71, 0x22, 0x4b, 0x0a, 0x10, 0x4c, 0x69,
	0x73, 0x74, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x69, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x37,
	0x0a, 0x08, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x1b, 0x2e, 0x70, 0x62, 0x2e, 0x67, 0x75, 0x62, 0x65, 0x72, 0x6e, 0x61, 0x74, 0x6f, 0x72,
	0x2e, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x52, 0x08, 0x70,
	0x6f, 0x6c, 0x69, 0x63, 0x69, 0x65, 0x73, 0x2a, 0x34, 0x0a, 0x12, 0x4d, 0x69, 0x73, 0x73, 0x69,
	0x6e, 0x67, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x08, 0x0a,
	0x04, 0x44, 0x45, 0x4e, 0x59, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x41, 0x4c, 0x4c, 0x4f, 0x57,
	0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x02, 0x32, 0xec, 0x02,
	0x0a, 0x0d, 0x45, 0x6e, 0x76, 0x6f, 0x79, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x56, 0x31, 0x12,
	0x71, 0x0a, 0x0d, 0x41, 0x70, 0x70, 0x6c, 0x79, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x69, 0x65, 0x73,
	0x12, 0x1f, 0x2e, 0x70, 0x62, 0x2e, 0x67, 0x75, 0x62, 0x65, 0x72, 0x6e, 0x61, 0x74, 0x6f, 0x72,
	0x2e, 0x41, 0x70, 0x70, 0x6c, 0x79, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x69, 0x65, 0x73, 0x52, 0x65,
	0x71, 0x1a, 0x20, 0x2e, 0x70, 0x62, 0x2e, 0x67, 0x75, 0x62, 0x65, 0x72, 0x6e, 0x61, 0x74, 0x6f,
	0x72, 0x2e, 0x41, 0x70, 0x70, 0x6c, 0x79, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x69, 0x65, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x22, 0x1d, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x17, 0x3a, 0x01, 0x2a, 0x22, 0x12,
	0x2f, 0x76, 0x31, 0x2f, 0x65, 0x6e, 0x76, 0x6f, 0x79, 0x2f, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x69,
	0x65, 0x73, 0x12, 0x7b, 0x0a, 0x0e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x6f, 0x6c, 0x69,
	0x63, 0x69, 0x65, 0x73, 0x12, 0x20, 0x2e, 0x70, 0x62, 0x2e, 0x67, 0x75, 0x62, 0x65, 0x72, 0x6e,
	0x61, 0x74, 0x6f, 0x72, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x6f, 0x6c, 0x69, 0x63,
	0x69, 0x65, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x21, 0x2e, 0x70, 0x62, 0x2e, 0x67, 0x75, 0x62, 0x65,
	0x72, 0x6e, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x6f, 0x6c,
	0x69, 0x63, 0x69, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x22, 0x24, 0x82, 0xd3, 0xe4, 0x93, 0x02,
	0x1e, 0x3a, 0x01, 0x2a, 0x22, 0x19, 0x2f, 0x76, 0x31, 0x2f, 0x65, 0x6e, 0x76, 0x6f, 0x79, 0x2f,
	0x70, 0x6f, 0x6c, 0x69, 0x63, 0x69, 0x65, 0x73, 0x2e, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12,
	0x6b, 0x0a, 0x0c, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x69, 0x65, 0x73, 0x12,
	0x1e, 0x2e, 0x70, 0x62, 0x2e, 0x67, 0x75, 0x62, 0x65, 0x72, 0x6e, 0x61, 0x74, 0x6f, 0x72, 0x2e,
	0x4c, 0x69, 0x73, 0x74, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x69, 0x65, 0x73, 0x52, 0x65, 0x71, 0x1a,
	0x1f, 0x2e, 0x70, 0x62, 0x2e, 0x67, 0x75, 0x62, 0x65, 0x72, 0x6e, 0x61, 0x74, 0x6f, 0x72, 0x2e,
	0x4c, 0x69, 0x73, 0x74, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x69, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x22, 0x1a, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x14, 0x12, 0x12, 0x2f, 0x76, 0x31, 0x2f, 0x65, 0x6e,
	0x76, 0x6f, 0x79, 0x2f, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x69, 0x65, 0x73, 0x42, 0x28, 0x5a, 0x23,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x67, 0x75, 0x62, 0x65, 0x72,
	0x6e, 0x61, 0x74, 0x6f, 0x72, 0x2d, 0x69, 0x6f, 0x2f, 0x67, 0x75, 0x62, 0x65, 0x72, 0x6e, 0x61,
	0x74, 0x6f, 0x72, 0x80, 0x01, 0x01, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_envoy_policy_proto_rawDescOnce sync.Once
	file_envoy_policy_proto_rawDescData = file_envoy_policy_proto_rawDesc
)

func file_envoy_policy_proto_rawDescGZIP() []byte {
	file_envoy_policy_proto_rawDescOnce.Do(func() {
		file_envoy_policy_proto_rawDescData = protoimpl.X.CompressGZIP(file_envoy_policy_proto_rawDescData)
	})
	return file_envoy_policy_proto_rawDescData
}

var file_envoy_policy_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_envoy_policy_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_envoy_policy_proto_goTypes = []interface{}{
	(MissingLimitAction)(0),    // 0: pb.gubernator.MissingLimitAction
	(*DomainPolicy)(nil),       // 1: pb.gubernator.DomainPolicy
	(*ApplyPoliciesReq)(nil),   // 2: pb.gubernator.ApplyPoliciesReq
	(*ApplyPoliciesResp)(nil),  // 3: pb.gubernator.ApplyPoliciesResp
	(*DeletePoliciesReq)(nil),  // 4: pb.gubernator.DeletePoliciesReq
	(*DeletePoliciesResp)(nil), // 5: pb.gubernator.DeletePoliciesResp
	(*ListPoliciesReq)(nil),    // 6: pb.gubernator.ListPoliciesReq
	(*ListPoliciesResp)(nil),   // 7: pb.gubernator.ListPoliciesResp
	(Algorithm)(0),             // 8: pb.gubernator.Algorithm
}
var file_envoy_policy_proto_depIdxs = []int32{
	8, // 0: pb.gubernator.DomainPolicy.algorithm:type_name -> pb.gubernator.Algorithm
	0, // 1: pb.gubernator.DomainPolicy.on_missing_limit:type_name -> pb.gubernator.MissingLimitAction
	1, // 2: pb.gubernator.ApplyPoliciesReq.policies:type_name -> pb.gubernator.DomainPolicy
	1, // 3: pb.gubernator.ApplyPoliciesResp.applied:type_name -> pb.gubernator.DomainPolicy
	1, // 4: pb.gubernator.ListPoliciesResp.policies:type_name -> pb.gubernator.DomainPolicy
	2, // 5: pb.gubernator.EnvoyPolicyV1.ApplyPolicies:input_type -> pb.gubernator.ApplyPoliciesReq
	4, // 6: pb.gubernator.EnvoyPolicyV1.DeletePolicies:input_type -> pb.gubernator.DeletePoliciesReq
	6, // 7: pb.gubernator.EnvoyPolicyV1.ListPolicies:input_type -> pb.gubernator.ListPoliciesReq
	3, // 8: pb.gubernator.EnvoyPolicyV1.ApplyPolicies:output_type -> pb.gubernator.ApplyPoliciesResp
	5, // 9: pb.gubernator.EnvoyPolicyV1.DeletePolicies:output_type -> pb.gubernator.DeletePoliciesResp
	7, // 10: pb.gubernator.EnvoyPolicyV1.ListPolicies:output_type -> pb.gubernator.ListPoliciesResp
	8, // [8:11] is the sub-list for method output_type
	5, // [5:8] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_envoy_policy_proto_init() }
func file_envoy_policy_proto_init() {
	if File_envoy_policy_proto != nil {
		return
	}
	file_gubernator_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_envoy_policy_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DomainPolicy); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_envoy_policy_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ApplyPoliciesReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_envoy_policy_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ApplyPoliciesResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_envoy_policy_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeletePoliciesReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_envoy_policy_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeletePoliciesResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_envoy_policy_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListPoliciesReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_envoy_policy_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListPoliciesResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_envoy_policy_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_envoy_policy_proto_goTypes,
		DependencyIndexes: file_envoy_policy_proto_depIdxs,
		EnumInfos:         file_envoy_policy_proto_enumTypes,
		MessageInfos:      file_envoy_policy_proto_msgTypes,
	}.Build()
	File_envoy_policy_proto = out.File
	file_envoy_policy_proto_rawDesc = nil
	file_envoy_policy_proto_goTypes = nil
	file_envoy_policy_proto_depIdxs = nil
}
