gubernator:

  fullnameOverride: {}
  nameOverride: {}
  priorityClassName: {}

  autoscaling:
    enabled: true
    methodScaling: "hpa"
    minReplicas: 2
    maxReplicas: 10
    cpuAverageUtilization: 50

  # keda example
  # https://keda.sh/docs/2.16/reference/scaledobject-spec
  # autoscaling:
  #   enabled: true
  #   methodScaling: "keda"
  #   minReplicas: 1
  #   maxReplicas: 2
  #   downscaleForbiddenWindowSeconds: 300
  #   upscaleForbiddenWindowSeconds: 15
  #   targetCPUUtilizationPercentage: 80
  #   targetMemoryUtilizationPercentage: 80

  replicaCount: 4

  image:
    repository: ghcr.io/gubernator-io/gubernator
    pullPolicy: IfNotPresent

    # By default tag is overriding appVersion from .Chart.yaml
    tag: "latest"

  # labels:
  #   a: "b"

  # Enabling gubernator debugger, default false
  # debug: true

  # Defines the mechanism to discover new pods
  # default is endpoints
  # watchPods: true

  server:
    http:
      port: "1050"
    grpc:
      port: "1051"
      # Defines the max age of a client connection
      # default is infinity
      # maxConnAgeSeconds: 30

  annotations: { }

  serviceAccount:
    create: false
#    name: "teste"

  nodeSelector: {}

  resources:
    requests:
      cpu: 100m
      memory: 150Mi

  serviceMonitor:
    create: false
    interval: 5s
    scrapeTimeout: 5s
