# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import envoy_policy_pb2 as envoy__policy__pb2


class EnvoyPolicyV1Stub(object):
    """Per-domain policy for the Envoy RateLimitService adapter. Policy holds how a
    domain is counted, never a limit value; limits arrive on each descriptor.
    Registered only when GUBER_ENVOY_RLS_ENABLED=true.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ApplyPolicies = channel.unary_unary(
                '/pb.gubernator.EnvoyPolicyV1/ApplyPolicies',
                request_serializer=envoy__policy__pb2.ApplyPoliciesReq.SerializeToString,
                response_deserializer=envoy__policy__pb2.ApplyPoliciesResp.FromString,
                )
        self.DeletePolicies = channel.unary_unary(
                '/pb.gubernator.EnvoyPolicyV1/DeletePolicies',
                request_serializer=envoy__policy__pb2.DeletePoliciesReq.SerializeToString,
                response_deserializer=envoy__policy__pb2.DeletePoliciesResp.FromString,
                )
        self.ListPolicies = channel.unary_unary(
                '/pb.gubernator.EnvoyPolicyV1/ListPolicies',
                request_serializer=envoy__policy__pb2.ListPoliciesReq.SerializeToString,
                response_deserializer=envoy__policy__pb2.ListPoliciesResp.FromString,
                )


class EnvoyPolicyV1Servicer(object):
    """Per-domain policy for the Envoy RateLimitService adapter. Policy holds how a
    domain is counted, never a limit value; limits arrive on each descriptor.
    Registered only when GUBER_ENVOY_RLS_ENABLED=true.
    """

    def ApplyPolicies(self, request, context):
        """Upserts each policy; broadcasts to all known peers; returns peers that did not ack.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeletePolicies(self, request, context):
        """Tombstones each domain; same propagation as apply.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListPolicies(self, request, context):
        """Returns this peer's current non-tombstoned policies.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EnvoyPolicyV1Servicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ApplyPolicies': grpc.unary_unary_rpc_method_handler(
                    servicer.ApplyPolicies,
                    request_deserializer=envoy__policy__pb2.ApplyPoliciesReq.FromString,
                    response_serializer=envoy__policy__pb2.ApplyPoliciesResp.SerializeToString,
            ),
            'DeletePolicies': grpc.unary_unary_rpc_method_handler(
                    servicer.DeletePolicies,
                    request_deserializer=envoy__policy__pb2.DeletePoliciesReq.FromString,
                    response_serializer=envoy__policy__pb2.DeletePoliciesResp.SerializeToString,
            ),
            'ListPolicies': grpc.unary_unary_rpc_method_handler(
                    servicer.ListPolicies,
                    request_deserializer=envoy__policy__pb2.ListPoliciesReq.FromString,
                    response_serializer=envoy__policy__pb2.ListPoliciesResp.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pb.gubernator.EnvoyPolicyV1', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class EnvoyPolicyV1(object):
    """Per-domain policy for the Envoy RateLimitService adapter. Policy holds how a
    domain is counted, never a limit value; limits arrive on each descriptor.
    Registered only when GUBER_ENVOY_RLS_ENABLED=true.
    """

    @staticmethod
    def ApplyPolicies(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pb.gubernator.EnvoyPolicyV1/ApplyPolicies',
            envoy__policy__pb2.ApplyPoliciesReq.SerializeToString,
            envoy__policy__pb2.ApplyPoliciesResp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeletePolicies(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pb.gubernator.EnvoyPolicyV1/DeletePolicies',
            envoy__policy__pb2.DeletePoliciesReq.SerializeToString,
            envoy__policy__pb2.DeletePoliciesResp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListPolicies(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pb.gubernator.EnvoyPolicyV1/ListPolicies',
            envoy__policy__pb2.ListPoliciesReq.SerializeToString,
            envoy__policy__pb2.ListPoliciesResp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
