# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: envoy_policy.proto
# Protobuf Python Version: 7.36.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    36,
    0,
    '',
    'envoy_policy.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
import gubernator_pb2 as gubernator__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x65nvoy_policy.proto\x12\rpb.gubernator\x1a\x1cgoogle/api/annotations.proto\x1a\x10gubernator.proto\"\xf9\x01\n\x0c\x44omainPolicy\x12\x16\n\x06\x64omain\x18\x01 \x01(\tR\x06\x64omain\x12\x36\n\talgorithm\x18\x02 \x01(\x0e\x32\x18.pb.gubernator.AlgorithmR\talgorithm\x12\x1a\n\x08\x62\x65havior\x18\x03 \x01(\x05R\x08\x62\x65havior\x12K\n\x10on_missing_limit\x18\x04 \x01(\x0e\x32!.pb.gubernator.MissingLimitActionR\x0eonMissingLimit\x12\x18\n\x07version\x18\x05 \x01(\x03R\x07version\x12\x16\n\x06origin\x18\x06 \x01(\tR\x06origin\"K\n\x10\x41pplyPoliciesReq\x12\x37\n\x08policies\x18\x01 \x03(\x0b\x32\x1b.pb.gubernator.DomainPolicyR\x08policies\"w\n\x11\x41pplyPoliciesResp\x12\x35\n\x07\x61pplied\x18\x01 \x03(\x0b\x32\x1b.pb.gubernator.DomainPolicyR\x07\x61pplied\x12+\n\x11unreachable_peers\x18\x02 \x03(\tR\x10unreachablePeers\"-\n\x11\x44\x65letePoliciesReq\x12\x18\n\x07\x64omains\x18\x01 \x03(\tR\x07\x64omains\"A\n\x12\x44\x65letePoliciesResp\x12+\n\x11unreachable_peers\x18\x01 \x03(\tR\x10unreachablePeers\"\x11\n\x0fListPoliciesReq\"K\n\x10ListPoliciesResp\x12\x37\n\x08policies\x18\x01 \x03(\x0b\x32\x1b.pb.gubernator.DomainPolicyR\x08policies*4\n\x12MissingLimitAction\x12\x08\n\x04\x44\x45NY\x10\x00\x12\t\n\x05\x41LLOW\x10\x01\x12\t\n\x05\x45RROR\x10\x02\x32\xec\x02\n\rEnvoyPolicyV1\x12q\n\rApplyPolicies\x12\x1f.pb.gubernator.ApplyPoliciesReq\x1a .pb.gubernator.ApplyPoliciesResp\"\x1d\x82\xd3\xe4\x93\x02\x17\"\x12/v1/envoy/policies:\x01*\x12{\n\x0e\x44\x65letePolicies\x12 .pb.gubernator.DeletePoliciesReq\x1a!.pb.gubernator.DeletePoliciesResp\"$\x82\xd3\xe4\x93\x02\x1e\"\x19/v1/envoy/policies.delete:\x01*\x12k\n\x0cListPolicies\x12\x1e.pb.gubernator.ListPoliciesReq\x1a\x1f.pb.gubernator.ListPoliciesResp\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/v1/envoy/policiesB(Z#github.com/gubernator-io/gubernator\x80\x01\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'envoy_policy_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z#github.com/gubernator-io/gubernator\200\001\001'
  _globals['_ENVOYPOLICYV1'].methods_by_name['ApplyPolicies']._loaded_options = None
  _globals['_ENVOYPOLICYV1'].methods_by_name['ApplyPolicies']._serialized_options = b'\202\323\344\223\002\027\"\022/v1/envoy/policies:\001*'
  _globals['_ENVOYPOLICYV1'].methods_by_name['DeletePolicies']._loaded_options = None
  _globals['_ENVOYPOLICYV1'].methods_by_name['DeletePolicies']._serialized_options = b'\202\323\344\223\002\036\"\031/v1/envoy/policies.delete:\001*'
  _globals['_ENVOYPOLICYV1'].methods_by_name['ListPolicies']._loaded_options = None
  _globals['_ENVOYPOLICYV1'].methods_by_name['ListPolicies']._serialized_options = b'\202\323\344\223\002\024\022\022/v1/envoy/policies'
  _globals['_MISSINGLIMITACTION']._serialized_start=745
  _globals['_MISSINGLIMITACTION']._serialized_end=797
  _globals['_DOMAINPOLICY']._serialized_start=86
  _globals['_DOMAINPOLICY']._serialized_end=335
  _globals['_APPLYPOLICIESREQ']._serialized_start=337
  _globals['_APPLYPOLICIESREQ']._serialized_end=412
  _globals['_APPLYPOLICIESRESP']._serialized_start=414
  _globals['_APPLYPOLICIESRESP']._serialized_end=533
  _globals['_DELETEPOLICIESREQ']._serialized_start=535
  _globals['_DELETEPOLICIESREQ']._serialized_end=580
  _globals['_DELETEPOLICIESRESP']._serialized_start=582
  _globals['_DELETEPOLICIESRESP']._serialized_end=647
  _globals['_LISTPOLICIESREQ']._serialized_start=649
  _globals['_LISTPOLICIESREQ']._serialized_end=666
  _globals['_LISTPOLICIESRESP']._serialized_start=668
  _globals['_LISTPOLICIESRESP']._serialized_end=743
  _globals['_ENVOYPOLICYV1']._serialized_start=800
  _globals['_ENVOYPOLICYV1']._serialized_end=1164
# @@protoc_insertion_point(module_scope)
