# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: peer.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import gubernator_pb2 as gubernator__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\npeer.proto\x12\rgubernator.v3\x1a\x10gubernator.proto\"M\n\x0e\x46orwardRequest\x12;\n\x08requests\x18\x01 \x03(\x0b\x32\x1f.gubernator.v3.RateLimitRequestR\x08requests\"T\n\x0f\x46orwardResponse\x12\x41\n\x0brate_limits\x18\x01 \x03(\x0b\x32 .gubernator.v3.RateLimitResponseR\nrateLimits\"I\n\rUpdateRequest\x12\x38\n\x07globals\x18\x01 \x03(\x0b\x32\x1e.gubernator.v3.UpdateRateLimitR\x07globals\"\xce\x01\n\x0fUpdateRateLimit\x12\x10\n\x03key\x18\x01 \x01(\tR\x03key\x12\x36\n\x05state\x18\x02 \x01(\x0b\x32 .gubernator.v3.RateLimitResponseR\x05state\x12\x36\n\talgorithm\x18\x03 \x01(\x0e\x32\x18.gubernator.v3.AlgorithmR\talgorithm\x12\x1a\n\x08\x64uration\x18\x04 \x01(\x03R\x08\x64uration\x12\x1d\n\ncreated_at\x18\x05 \x01(\x03R\tcreatedAtB%Z#github.com/gubernator-io/gubernatorb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'peer_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z#github.com/gubernator-io/gubernator'
  _globals['_FORWARDREQUEST']._serialized_start=47
  _globals['_FORWARDREQUEST']._serialized_end=124
  _globals['_FORWARDRESPONSE']._serialized_start=126
  _globals['_FORWARDRESPONSE']._serialized_end=210
  _globals['_UPDATEREQUEST']._serialized_start=212
  _globals['_UPDATEREQUEST']._serialized_end=285
  _globals['_UPDATERATELIMIT']._serialized_start=288
  _globals['_UPDATERATELIMIT']._serialized_end=494
# @@protoc_insertion_point(module_scope)
