# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: peers.proto
# Protobuf Python Version: 7.36.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    36,
    0,
    '',
    'peers.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import gubernator_pb2 as gubernator__pb2
import envoy_policy_pb2 as envoy__policy__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bpeers.proto\x12\rpb.gubernator\x1a\x10gubernator.proto\x1a\x12\x65nvoy_policy.proto\"O\n\x14GetPeerRateLimitsReq\x12\x37\n\x08requests\x18\x01 \x03(\x0b\x32\x1b.pb.gubernator.RateLimitReqR\x08requests\"V\n\x15GetPeerRateLimitsResp\x12=\n\x0brate_limits\x18\x01 \x03(\x0b\x32\x1c.pb.gubernator.RateLimitRespR\nrateLimits\"Q\n\x14UpdatePeerGlobalsReq\x12\x39\n\x07globals\x18\x01 \x03(\x0b\x32\x1f.pb.gubernator.UpdatePeerGlobalR\x07globals\"\xcd\x01\n\x10UpdatePeerGlobal\x12\x10\n\x03key\x18\x01 \x01(\tR\x03key\x12\x34\n\x06status\x18\x02 \x01(\x0b\x32\x1c.pb.gubernator.RateLimitRespR\x06status\x12\x36\n\talgorithm\x18\x03 \x01(\x0e\x32\x18.pb.gubernator.AlgorithmR\talgorithm\x12\x1a\n\x08\x64uration\x18\x04 \x01(\x03R\x08\x64uration\x12\x1d\n\ncreated_at\x18\x05 \x01(\x03R\tcreatedAt\"\x17\n\x15UpdatePeerGlobalsResp\"[\n\nPeerPolicy\x12\x33\n\x06policy\x18\x01 \x01(\x0b\x32\x1b.pb.gubernator.DomainPolicyR\x06policy\x12\x18\n\x07\x64\x65leted\x18\x02 \x01(\x08R\x07\x64\x65leted\"N\n\x15UpdatePeerPoliciesReq\x12\x35\n\x08policies\x18\x01 \x03(\x0b\x32\x19.pb.gubernator.PeerPolicyR\x08policies\"\x18\n\x16UpdatePeerPoliciesResp\"\x14\n\x12GetPeerPoliciesReq\"L\n\x13GetPeerPoliciesResp\x12\x35\n\x08policies\x18\x01 \x03(\x0b\x32\x19.pb.gubernator.PeerPolicyR\x08policies2\x8e\x03\n\x07PeersV1\x12`\n\x11GetPeerRateLimits\x12#.pb.gubernator.GetPeerRateLimitsReq\x1a$.pb.gubernator.GetPeerRateLimitsResp\"\x00\x12`\n\x11UpdatePeerGlobals\x12#.pb.gubernator.UpdatePeerGlobalsReq\x1a$.pb.gubernator.UpdatePeerGlobalsResp\"\x00\x12\x63\n\x12UpdatePeerPolicies\x12$.pb.gubernator.UpdatePeerPoliciesReq\x1a%.pb.gubernator.UpdatePeerPoliciesResp\"\x00\x12Z\n\x0fGetPeerPolicies\x12!.pb.gubernator.GetPeerPoliciesReq\x1a\".pb.gubernator.GetPeerPoliciesResp\"\x00\x42(Z#github.com/gubernator-io/gubernator\x80\x01\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'peers_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z#github.com/gubernator-io/gubernator\200\001\001'
  _globals['_GETPEERRATELIMITSREQ']._serialized_start=68
  _globals['_GETPEERRATELIMITSREQ']._serialized_end=147
  _globals['_GETPEERRATELIMITSRESP']._serialized_start=149
  _globals['_GETPEERRATELIMITSRESP']._serialized_end=235
  _globals['_UPDATEPEERGLOBALSREQ']._serialized_start=237
  _globals['_UPDATEPEERGLOBALSREQ']._serialized_end=318
  _globals['_UPDATEPEERGLOBAL']._serialized_start=321
  _globals['_UPDATEPEERGLOBAL']._serialized_end=526
  _globals['_UPDATEPEERGLOBALSRESP']._serialized_start=528
  _globals['_UPDATEPEERGLOBALSRESP']._serialized_end=551
  _globals['_PEERPOLICY']._serialized_start=553
  _globals['_PEERPOLICY']._serialized_end=644
  _globals['_UPDATEPEERPOLICIESREQ']._serialized_start=646
  _globals['_UPDATEPEERPOLICIESREQ']._serialized_end=724
  _globals['_UPDATEPEERPOLICIESRESP']._serialized_start=726
  _globals['_UPDATEPEERPOLICIESRESP']._serialized_end=750
  _globals['_GETPEERPOLICIESREQ']._serialized_start=752
  _globals['_GETPEERPOLICIESREQ']._serialized_end=772
  _globals['_GETPEERPOLICIESRESP']._serialized_start=774
  _globals['_GETPEERPOLICIESRESP']._serialized_end=850
  _globals['_PEERSV1']._serialized_start=853
  _globals['_PEERSV1']._serialized_end=1251
# @@protoc_insertion_point(module_scope)
